# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Belform Insulation
# Description of the Site
description: BELFORM INSUL-PHEN,BELFORM STYROFOAM INTERLOCKING SYSTEM & TRYMER XP PIPE INSULATION & FITTINGS
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/hero.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: belform@gmail.com
facebook_username: belform
twitter_username: belform
instagram_username: belform
linkedin_username: belform
github_username:  belform
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Belform

# Name of the Author
author-name: Belform Insulation Canada
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: We manufacture a wide variety of high-quality mechanical insulation products. Available in Resolco Phenolic, Styrofoam, Urethane, and Cellular Glass Foam, Designed specifically for condensation control and for minimizing heat gain (loss). Most of our products are manufactured with tongue and groove and shiplapped edges to increase their insulation value.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/belform

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
